### PR TITLE
Avoid leaking passwords into shell history and audits events by supporting reading passwords from stdin

### LINKED ISSUE #882: Avoid leaking passwords into shell history and audits events by supporting reading passwords from stdin
**Describe the bug**
When using `mongocli` via a script it is sometimes necessary to provide a `--password` argument on the command line in order to specify a sensitive value. This sensitive value will then appear in both the terminal history files as well as potentially appearing in `auditd` (for Linux based systems, and potentially others) as part of their records. For environments where including sensitive values in these locations is undesirable the existing mechanism is not so great and hard to work around. 

**To Reproduce**
1. Run `mongocli atlas dbuser create --username ${USER} --role clusterMonitor,backup --projectId ${PROJECT} --password MySensitiveValue`
2.  Check shell history for password

**Expected behavior**
A mechanism to pass the password into the command either via a pipe or via a file or environment variable (does viper/cobra already enable this?).

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
A potential solution (add a `--passwordStdin` flag to various commands) is available in https://github.com/mongodb/mongocli/pull/881

### PR DESCRIPTION
**Pull request by patdowney**
## Proposed changes

Jira: CLOUDP-106015

closes #882 

Adds a `--passwordStdin` flag to the appropriate `mongocli` commands in order to avoid the specified password showing up in terminal history or system audit records by allowing it to be passed in via `stdin`.

This will allow things like
```
$ vault read -field=value my/path/to/secret | mongocli atlas dbuser create --username ${USER} --role clusterMonitor,backup --projectId ${PROJECT} --passwordStdin
```

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have updated [e2e/E2E-TESTS.md](e2e/E2E-TESTS.md) (if a new command or e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

File: internal/prompt/prompt_test.go [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package prompt
```
Comment (gssbzn) [inline internal/prompt/prompt_test.go:1]: let's please add 
```suggestion

//go:build unit
// +build unit

package prompt
```
```suggestion
package prompt
```

**Review by gssbzn — CHANGES_REQUESTED** [review]
sorry for the delay on this

one initial things that's causing our internal CI to fail, the new files are missing the copyright header, you can fix this by running `make addcopy`

**Review by gssbzn — COMMENTED** [review]
another failure from our CI
```
 [2021/11/03 10:51:51.817] FAILURE: Failed ()
 [2021/11/03 10:51:51.817] === RUN   TestDBUsers/Create
 [2021/11/03 10:51:51.817]     dbusers_test.go:65:
 [2021/11/03 10:51:51.817]         	Error Trace:	dbusers_test.go:202
 [2021/11/03 10:51:51.817]         	            				dbusers_test.go:65
 [2021/11/03 10:51:51.817]         	Error:      	Not equal:
 [2021/11/03 10:51:51.817]         	            	expected: "passW0rd"
 [2021/11/03 10:51:51.817]         	            	actual  : ""
 [2021/11/03 10:51:51.817] 
 [2021/11/03 10:51:51.817]         	            	Diff:
 [2021/11/03 10:51:51.817]         	            	--- Expected
 [2021/11/03 10:51:51.817]         	            	+++ Actual
 [2021/11/03 10:51:51.817]         	            	@@ -1 +1 @@
 [2021/11/03 10:51:51.817]         	            	-passW0rd
 [2021/11/03 10:51:51.817]         	            	+
 [2021/11/03 10:51:51.817]         	Test:       	TestDBUsers/Create
 [2021/11/03 10:51:51.817]     --- FAIL: TestDBUsers/Create (0.10s)
```

File: internal/prompt/prompt.go [hunk 2]
```diff
@@ -16,10 +16,28 @@ package prompt
...
+}
+
+// isTerminalInput returns true if input device is a terminal
+// Will return false in the case of the reader not being a terminal.
+func IsTerminalInputStream(stream io.Reader) bool {
+	if inputStream, ok := stream.(*os.File); ok {
+		return isatty.IsTerminal(inputStream.Fd()) || isatty.IsCygwinTerminal(inputStream.Fd())
+	}
+	return false
+}
```
Comment (gssbzn) [inline internal/prompt/prompt.go:39]: [nit] good on the idea but I would avoid the global `IsTerminalInput` given you always call this in the context of a cobra command, then on the usage of `IsTerminalInputStream(stream io.Reader)` you always call it with `os.Stdin` this may introduce some edge-cases given the cobra context, so to make this correct you should call IsTerminal always with `cmd.InOrStdin()`

I think I mentioned this before but I believe the ideal approach would be something similar to OutputOpts https://github.com/mongodb/mongocli/blob/9c641961e016b06040b06c0ccff9adbb3a4e701a/internal/cli/output_opts.go#L41-L45

**Comment by gssbzn** [comment]
Also before we can accept your contribution we need you to sign our [CLA](https://www.mongodb.com/legal/contributor-agreement)

**Comment by patdowney** [comment]
Thanks @gssbzn . I'll address your comments, hopefully this weekend. I thought I'd already signed the CLA?

**Comment by gssbzn** [comment]
> I thought I'd already signed the CLA?

I could not find your github username on our database, if you can double check if you did that'd be great

**Comment by patdowney** [comment]
Think I've figured it out, I signed the form but didn't click the further confirmation link that's sent afterwards. Will take care of that this weekend as well

**Comment by patdowney** [comment]
Actually, have just found the confirmed email. I signed it on 2021-10-02, GitHub username on the form is dioadconsulting maybe I got that bit wrong

**Comment by gssbzn** [comment]
> GitHub username on the form is dioadconsulting maybe I got that bit wrong

Thanks that was it, I can see `dioadconsulting`, would you mind signing again with the correct username?

File: internal/prompt/prompt.go (hunk 2 above)
Comment (patdowney) [reply internal/prompt/prompt.go]: Ah right, I didn't quite get what you were suggesting. I've added an `InputOpts` struct and call it where I think is appropriate for its use - I've also removed the functions from `prompt.go` as they're redundant now. Is that what you were looking for?

I've also reverted my changes to `internal/cli/atlas/dbusers/update.go` as I didn't understand that not specifying a password is a valid use of the command, so the regular `Prompt` work flow wouldn't work.

File: e2e/atlas/dbusers_test.go [hunk 3]
```diff
@@ -30,23 +31,37 @@ import (
...
+	return fmt.Sprintf("user-%v", n), nil
+}
+
+func TestDBUsers(t *testing.T) {
+	username, err := generateUsername()
+	if err != nil {
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	stdinUsername, err := generateUsername()
```
Comment (gssbzn) [inline e2e/atlas/dbusers_test.go:55]: [nit] let's move this as close as possible to where is used

File: e2e/atlas/dbusers_test.go [hunk 4]
```diff
@@ -55,27 +70,30 @@ func TestDBUsers(t *testing.T) {
...
+			dbusersEntity,
+			"create",
+			"atlasAdmin",
+			"--deleteAfter", time.Now().AddDate(0, 0, 1).Format(time.RFC3339),
+			"--username", stdinUsername,
+			"--scope", scopeClusterDataLake,
+			"-o=json",
+		)
+
+		passwordStdin := bytes.NewBuffer([]byte(fmt.Sprintf("%s", userPassword)))
```
Comment (gssbzn) [inline e2e/atlas/dbusers_test.go:93]: [q] wouldn't this be the same as 
```suggestion
		passwordStdin := bytes.NewBuffer([]byte(userPassword))
```

File: e2e/atlas/dbusers_test.go [hunk 5]
```diff
@@ -30,23 +31,37 @@ import (
...
-func TestDBUsers(t *testing.T) {
+func generateUsername() (string, error) {
 	n, err := e2e.RandInt(1000)
+	if err != nil {
+		return "", err
+	}
+	return fmt.Sprintf("user-%v", n), nil
+}
+
+func TestDBUsers(t *testing.T) {
```
Comment (gssbzn) [inline e2e/atlas/dbusers_test.go:49]: [nit and probably not blocking] I would structure this similar to how we structured clusters tests one `TestDBUserWithFlags` and one `TestBBUserWithStdIn` both doing the full CRUD to avoid confusion with the double delete I saw bellow and that a failure in one way is not a failure in both

File: e2e/atlas/dbusers_test.go [hunk 6]
```diff
@@ -159,22 +180,52 @@ func TestDBUsers(t *testing.T) {
...
+	t.Helper()
 
-		expected := fmt.Sprintf("DB user '%s' deleted\n", username)
-		assert.Equal(t, expected, string(resp))
-	})
+	cmd.Env = os.Environ()
+
+	resp, err := cmd.CombinedOutput()
+	a := assert.New(t)
+	a.NoError(err)
```
Comment (gssbzn) [inline e2e/atlas/dbusers_test.go:195]: [nit] you want `require` here so it doesn't run any other test
```suggestion
	require.NoError(t, err)
	a := assert.New(t)
```

File: e2e/atlas/dbusers_test.go [hunk 7]
```diff
@@ -159,22 +180,52 @@ func TestDBUsers(t *testing.T) {
...
+
+	var user mongodbatlas.DatabaseUser
+	if err := json.Unmarshal(resp, &user); err != nil {
+		t.Fatalf("unexpected error: %v", err)
+	}
```
Comment (gssbzn) [inline e2e/atlas/dbusers_test.go:200]: similar to above this can be replaced with `require.NoError`

**Comment by gssbzn** [comment]
Thanks again for all the changes, code looks good I have some recommendations on the tests and I'm waiting for our CI ro run to make sure there's no other thing to look at

File: e2e/atlas/dbusers_test.go (hunk 4 above)
Comment (gssbzn) [reply e2e/atlas/dbusers_test.go:93]: yep, the linting got it

File: e2e/atlas/ldap_test.go [hunk 8]
```diff
@@ -180,3 +216,36 @@ func TestLDAP(t *testing.T) {
...
+
+	cmd.Env = os.Environ()
+	resp, err := cmd.CombinedOutput()
+	require.NoError(t, err, string(resp))
+
+	a := assert.New(t)
+	var configuration mongodbatlas.LDAPConfiguration
+	if err := json.Unmarshal(resp, &configuration); a.NoError(err) {
+		a.Equal(pending, configuration.Status)
+		a.Equal(ldapBindPassword, configuration.LDAP.BindPassword)
```
Comment (gssbzn) [inline e2e/atlas/ldap_test.go:231]: this is producing a segmentation fault on our tests
```
 [2021/11/08 23:15:08.699] FAILURE: Failed ()
 [2021/11/08 23:15:08.699] === RUN   TestLDAP/Verify
 [2021/11/08 23:15:08.699]     --- FAIL: TestLDAP/Verify (0.12s)
 [2021/11/08 23:15:08.699] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
 [2021/11/08 23:15:08.699] 	panic: runtime error: invalid memory address or nil pointer dereference
 [2021/11/08 23:15:08.699] [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x59fc0e]
 [2021/11/08 23:15:08.699] goroutine 11 [running]:
 [2021/11/08 23:15:08.699] testing.tRunner.func1.2({0x5c0e80, 0x76a460})
 [2021/11/08 23:15:08.699] 	/opt/golang/go1.17/src/testing/testing.go:1209 +0x24e
 [2021/11/08 23:15:08.699] testing.tRunner.func1()
 [2021/11/08 23:15:08.699] 	/opt/golang/go1.17/src/testing/testing.go:1212 +0x218
 [2021/11/08 23:15:08.699] panic({0x5c0e80, 0x76a460})
 [2021/11/08 23:15:08.699] 	/opt/golang/go1.17/src/runtime/panic.go:1038 +0x215
 [2021/11/08 23:15:08.699] github.com/mongodb/mongocli/e2e/atlas_test.testLDAPVerifyCmd(0xc00017a340, 0xc000136c60)
 [2021/11/08 23:15:08.699] 	/data/mci/dc27fd5560d63c8af9dc6b6760559cb7/src/github.com/mongodb/mongocli/e2e/atlas/ldap_test.go:231 +0x1ae
 [2021/11/08 23:15:08.699] github.com/mongodb/mongocli/e2e/atlas_test.TestLDAP.func1(0x1)
 [2021/11/08 23:15:08.699] 	/data/mci/dc27fd5560d63c8af9dc6b6760559cb7/src/github.com/mongodb/mongocli/e2e/atlas/ldap_test.go:64 +0x212
 [2021/11/08 23:15:08.699] testing.tRunner(0xc00017a340, 0xc000079d70)
 [2021/11/08 23:15:08.699] 	/opt/golang/go1.17/src/testing/testing.go:1259 +0x102
 [2021/11/08 23:15:08.699] created by testing.(*T).Run
 [2021/11/08 23:15:08.699] 	/opt/golang/go1.17/src/testing/testing.go:1306 +0x35a
```

Comment (patdowney) [reply e2e/atlas/ldap_test.go]: The `LDAP` property isn't populated in the `PENDING` repsonse, which is why it's segfaulted. I've removed the assertion against `.LDAP.BindPassword`

File: e2e/atlas/ldap_test.go [hunk 9]
```diff
@@ -167,16 +154,117 @@ func TestLDAP(t *testing.T) {
...
+
+		testLDAPSaveCmd(t, cmd)
+	})
+
+	t.Run("Delete", func(t *testing.T) {
+		testLDAPDelete(t, cliPath, g.projectID)
+	})
+}
+
+func testLDAPDelete(t *testing.T, cliPath string, projectID string) {
```
Comment (andreaangiolillo) [inline e2e/atlas/ldap_test.go:226]:
```suggestion
func testLDAPDelete(t *testing.T, cliPath, projectID string) {
```

**Comment by colm-quinn** [comment]
This is failing the linting check currently:
```
  Error: paramTypeCombine: func(t *testing.T, cliPath string, projectID string) could be replaced with func(t *testing.T, cliPath, projectID string) (gocritic)
```

I'd recommend running those checks locally with `make lint` and/or `make fix-lint` to catch the issues as you are committing changes.

File: internal/cli/atlas/dbusers/create.go [hunk 10]
```diff
@@ -131,7 +139,7 @@ func (opts *CreateOpts) validate() error {
 		return errors.New("missing role for the user")
 	}
 
-	if opts.isExternal() && opts.password != "" {
+	if opts.isExternal() && (opts.password != "") {
```
Comment (colm-quinn) [inline internal/cli/atlas/dbusers/create.go:142]: [q/np] Do we need the extra brackets here?

File: internal/cli/atlas/security/ldap/save.go [hunk 11]
```diff
@@ -65,6 +68,23 @@ func (opts *SaveOpts) Run() error {
...
+		return err
+	}
+
+	prompt := &survey.Password{
+		Message: "Password:",
+	}
+
+	return survey.AskOne(prompt, &opts.bindPassword)
+}
+
```
Comment (andreaangiolillo) [inline internal/cli/atlas/security/ldap/save.go:87]: [nit] I think we could add this function under `InputOpts` and pass the `password` as an input parameter so that we can reuse this piece of code. Then you can call this function in any commands that require this prompt message

**Review by andreaangiolillo — COMMENTED** [review]
LGTM. You just need to fix the lint issue.

File: internal/cli/atlas/dbusers/create.go (hunk 10 above)
Comment (patdowney) [reply internal/cli/atlas/dbusers/create.go]: thanks @colm-quinn. Addressed in latest.

File: e2e/atlas/ldap_test.go (hunk 9 above)
Comment (patdowney) [reply e2e/atlas/ldap_test.go]: thanks @andreaangiolillo . Addressed in latest.

File: internal/cli/atlas/security/ldap/save.go (hunk 11 above)
Comment (patdowney) [reply internal/cli/atlas/security/ldap/save.go:87]: @andreaangiolillo - is this a change you'd like me to introduce as part of this PR?

Comment (andreaangiolillo) [reply internal/cli/atlas/security/ldap/save.go:87]: It is up to you. We can add this improvement in another PR if you want ; )

File: e2e/atlas/ldap_test.go [hunk 12]
```diff
@@ -134,15 +128,8 @@ func TestLDAP(t *testing.T) {
...
-		cmd.Env = os.Environ()
-		resp, err := cmd.CombinedOutput()
-		require.NoError(t, err, string(resp))
 
-		a := assert.New(t)
-		var configuration mongodbatlas.LDAPConfiguration
-		if err := json.Unmarshal(resp, &configuration); a.NoError(err) {
-			a.Equal(ldapHostname, configuration.LDAP.Hostname)
-		}
+		testLDAPSaveCmd(t, cmd)
```
Comment (gssbzn) [inline e2e/atlas/ldap_test.go:132]:
```
 [2021/11/15 15:41:25.385] FAILURE: Failed ()
 [2021/11/15 15:41:25.385] === RUN   TestLDAPWithFlags/Save
 [2021/11/15 15:41:25.385]     ldap_test.go:132:
 [2021/11/15 15:41:25.385]         	Error Trace:	ldap_test.go:270
 [2021/11/15 15:41:25.385]         	            				ldap_test.go:132
 [2021/11/15 15:41:25.385]         	Error:      	Not equal:
 [2021/11/15 15:41:25.385]         	            	expected: "admin"
 [2021/11/15 15:41:25.385]         	            	actual  : ""
 [2021/11/15 15:41:25.385] 
 [2021/11/15 15:41:25.385]         	            	Diff:
 [2021/11/15 15:41:25.385]         	            	--- Expected
 [2021/11/15 15:41:25.385]         	            	+++ Actual
 [2021/11/15 15:41:25.385]         	            	@@ -1 +1 @@
 [2021/11/15 15:41:25.385]         	            	-admin
 [2021/11/15 15:41:25.385]         	            	+
 [2021/11/15 15:41:25.385]         	Test:       	TestLDAPWithFlags/Save
 [2021/11/15 15:41:25.385]     --- FAIL: TestLDAPWithFlags/Save (0.09s)
```

File: e2e/atlas/ldap_test.go [hunk 13]
```diff
@@ -167,16 +154,119 @@ func TestLDAP(t *testing.T) {
...
+			"cn={0},ou=engineering,dc=example,dc=com",
+			"--projectId", g.projectID,
+			"-o",
+			"json",
+		)
+
+		passwordStdin := bytes.NewBuffer([]byte(ldapBindPassword))
+		cmd.Stdin = passwordStdin
+
+		testLDAPSaveCmd(t, cmd)
```
Comment (gssbzn) [inline e2e/atlas/ldap_test.go:218]:
```

 [2021/11/15 15:41:25.641] FAILURE: Failed ()
 [2021/11/15 15:41:25.641] === RUN   TestLDAPWithStdin/Save
 [2021/11/15 15:41:25.641]     ldap_test.go:218:
 [2021/11/15 15:41:25.641]         	Error Trace:	ldap_test.go:270
 [2021/11/15 15:41:25.641]         	            				ldap_test.go:218
 [2021/11/15 15:41:25.641]         	Error:      	Not equal:
 [2021/11/15 15:41:25.641]         	            	expected: "admin"
 [2021/11/15 15:41:25.641]         	            	actual  : ""
 [2021/11/15 15:41:25.641] 
 [2021/11/15 15:41:25.641]         	            	Diff:
 [2021/11/15 15:41:25.641]         	            	--- Expected
 [2021/11/15 15:41:25.641]         	            	+++ Actual
 [2021/11/15 15:41:25.641]         	            	@@ -1 +1 @@
 [2021/11/15 15:41:25.641]         	            	-admin
 [2021/11/15 15:41:25.641]         	            	+
 [2021/11/15 15:41:25.641]         	Test:       	TestLDAPWithStdin/Save
 [2021/11/15 15:41:25.641]     --- FAIL: TestLDAPWithStdin/Save (0.10s)
```

File: e2e/cloud_manager/dbusers_test.go [hunk 14]
```diff
@@ -72,16 +73,23 @@ func TestDBUsers(t *testing.T) {
...
+			dbUsersEntity,
+			"create",
+			"--username="+username,
+			"--role=readWriteAnyDatabase",
+			"--mechanisms=SCRAM-SHA-256")
+
+		passwordStdin := bytes.NewBuffer([]byte("passW0rd"))
+		cmd.Stdin = passwordStdin
+
+		testCreatePasswordCmd(t, cmd)
```
Comment (gssbzn) [inline e2e/cloud_manager/dbusers_test.go:92]: [2021/11/15 15:28:14.823] FAILURE: Failed ()
 [2021/11/15 15:28:14.823] === RUN   TestDBUsers/CreatePasswordStdin
 [2021/11/15 15:28:14.823]     dbusers_test.go:92: unexpected error: exit status 1, resp: Error: PUT https://cloud-dev.mongodb.com/api/public/v1.0/groups/61927b10ab680d0601bf033a/automationConfig: 400 (request "") Invalid config: Each auth.usersWanted must have a unique user id. Duplicate found: user-126@admin
 [2021/11/15 15:28:14.823]     --- FAIL: TestDBUsers/CreatePasswordStdin (0.15s)

Comment (patdowney) [reply e2e/cloud_manager/dbusers_test.go:92]: ah, same stuff as the atlast tests, will take a look at pulling these out into `TestDBUsersWithFlags` and `TestDBUsersWithStdin` too.

**Review by gssbzn — APPROVED** [review]
🎉  thanks so much @patdowney 
Tests are looking good and I can confirm the CLA has been signed, we'll be merging this shortly

**Review by colm-quinn — APPROVED** [review]
LGTM, thanks for those changes and working through all the comments - this is a great contribution!

**Comment by gssbzn** [comment]
Internal ticket: CLOUDP-106015

**Review by melissamahoney-mongodb — APPROVED** [review]

**Comment by patdowney** [comment]
Great 👍 Thanks for your patience!
